### Login user:
POST http://localhost:3000/auth/login
content-type: application/json

{
  "email": "kondvik@gmail.com",
  "password": "password"
}

### Login attempt with invalid data:
POST http://localhost:3000/auth/login
content-type: application/json

{}