### Login user:
POST http://localhost:3000/auth/login
content-type: application/json

{
  "email": "johndoe@domain.com",
  "password": "password"
}

### Login admin:
POST http://localhost:3000/auth/login
content-type: application/json

{
  "email": "admin@admin.com",
  "password": "password"
}

### Login attempt with invalid data:
POST http://localhost:3000/auth/login
content-type: application/json

{}