### Register user:
POST http://localhost:3000/api/users
content-type: application/json

{
  "email": "kondvik3@gmail.com",
  "password": "password",
  "name": "Tamas Peter"
}

### Register attempt with invalid data:
POST http://localhost:3000/api/users
content-type: application/json

{}